const DATABASE_NAME = '@gameplay';

// @app:collection
const COLLECTION_USER_AUTH = `${DATABASE_NAME}:user-auth`;
const COLLECTION_APPOINTMENTS = `${DATABASE_NAME}:appointments`;
const COLLECTION_LOCALE = `${DATABASE_NAME}:locale`;
const COLLECTION_THEME = `${DATABASE_NAME}:theme`;

export {
  COLLECTION_USER_AUTH,
  COLLECTION_APPOINTMENTS,
  COLLECTION_LOCALE,
  COLLECTION_THEME,
};
